export {
  ANTE,
  BET_MULTIPLE,
  CAP,
  CURRENCY_NAME,
  DAILY_AMOUNT,
  DAILY_COOLDOWN_MS,
  HISTORY_LIMIT,
  LOBBY_TTL_MS,
  MAX_PLAYERS,
  MIN_BET_STEP,
  MIN_JOIN_BALANCE,
  MIN_PLAYERS,
  TURN_SECONDS,
} from "./engine/constants";

export const RUNOUT_STEP_MS = 2000;
export const RESET_CONFIRM_TTL_MS = 5 * 60 * 1000;
export const EDIT_MIN_INTERVAL_MS = 1000;
export const SEND_CAP_PER_UPDATE = 16;
export const USER_ACTION_INTERVAL_MS = 1000;
export const PRUNE_UPDATES_AFTER_MS = 7 * 24 * 60 * 60 * 1000;
export const PRUNE_UPDATES_THRESHOLD = 5000;
export const OWNER_ALERT_INTERVAL_MS = 60 * 60 * 1000;
